### ISSUE TITLE
Users calling the bot to a subreddit it is banned on receive no feedback

### ISSUE THREAD

**Issue by TSATPWTCOTTTADC** [crombird/meta#22]
It may be good to send a PM to the user explaining why there was no response.

Investing more effort into PM functionality than that might not be worth the effort as the [prominence](https://www.reddit.com/r/redditmobile/comments/g3yove/android2020130263353_did_the_send_message_option/fo7g39h/) of PMs on Reddit in general is being reduced - The UIs of New Reddit and official mobile apps already lack PM buttons.

The bot's current account got banned from r/TwoSentenceHorror recently (Ban reason - "Bot."). The current account has commented on that subreddit five times.

**Comment by smlt** [comment]
I think I'll go ahead and close this one. Like you mentioned in the description, the prominence of PMs on reddit is slowly decreasing, with no API available for chat. I feel like the bot is used more for the purpose of effectively linking pages for others rather than as a bot for searching.

On a related note, this would definitely come in handy for how people are using the bot on discord, especially with debugging permission issues, which seems to be something that comes up a lot. I'll create a separate issue for that, though.
